version: '3.8'

services:
  python:
    build: server
    entrypoint: ["python", "app.py"]
    ports:
      - "5000:5000"
    volumes:
      - ./server/src:/code

  db:
    image: mongo
    env_file: .env.dev
    ports:
      - "27017:27017"